# Generated by Django 2.0.7 on 2018-07-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0002_textfile_protest'),
    ]

    operations = [
        migrations.AddField(
            model_name='textfile',
            name='filename',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
