# Generated by Django 2.0.7 on 2018-07-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0003_textfile_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='textfile',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
