# Generated by Django 2.0.7 on 2018-07-19 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0005_annotator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotator',
            name='text_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classify.TextFile'),
        ),
        migrations.AlterField(
            model_name='annotator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
