# Generated by Django 2.0.7 on 2018-07-19 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0006_auto_20180719_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotator',
            name='text_file',
        ),
    ]
