# Generated by Django 2.0.7 on 2018-07-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0008_annotator_annotext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotator',
            name='annotext',
        ),
        migrations.AddField(
            model_name='annotator',
            name='annotext',
            field=models.ManyToManyField(to='classify.TextFile'),
        ),
    ]
