# Generated by Django 2.0.7 on 2018-07-19 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classify', '0009_auto_20180719_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotator',
            name='annotext',
        ),
        migrations.RemoveField(
            model_name='annotator',
            name='user',
        ),
        migrations.AddField(
            model_name='textfile',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Annotator',
        ),
    ]
