# Generated by Django 2.0.7 on 2018-07-24 09:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0010_auto_20180719_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textfile',
            name='is_checked',
        ),
        migrations.RemoveField(
            model_name='textfile',
            name='protest',
        ),
        migrations.RemoveField(
            model_name='textfile',
            name='user',
        ),
        migrations.AddField(
            model_name='textfile',
            name='json_var',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=' \n    "user": [\n\t{\n\t\t"is_checked":false,\n\t\t"is_protest":false\n\t}],\n\t"new_user": [\n\t{\n\t\t"is_checked":false,\n\t\t"is_protest":false\n\t}]\n    }\n    \n    '),
        ),
    ]
