# Generated by Django 2.0.7 on 2018-07-24 11:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0011_auto_20180724_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textfile',
            name='json_var',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='{"newuser": {"isprotest": false, "ischecked": false}, "user": {"isprotest": false, "ischecked": false}}'),
        ),
    ]
