# Generated by Django 2.0.7 on 2018-07-24 12:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0013_auto_20180724_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textfile',
            name='info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'newuser': {'ischecked': False, 'isprotest': False}, 'user': {'ischecked': False, 'isprotest': False}}),
        ),
    ]
