# Generated by Django 2.0.7 on 2018-07-26 11:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0014_auto_20180724_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textfile',
            name='info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[{'ischecked': False, 'isprotest': False, 'username': 'user'}, {'ischecked': False, 'isprotest': False, 'username': 'new_user'}]),
        ),
    ]
