# Generated by Django 2.0.7 on 2018-07-27 08:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0015_auto_20180726_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textfile',
            name='info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=({'isprotest': False, 'username': 'user'}, {'isprotest': False, 'username': 'new_user'})),
        ),
    ]
