# Generated by Django 2.0.7 on 2018-07-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0017_auto_20180727_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textfile',
            name='info',
        ),
        migrations.AddField(
            model_name='textfile',
            name='newuser',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='textfile',
            name='user',
            field=models.BooleanField(default=None),
        ),
    ]
