# Generated by Django 2.1 on 2018-08-13 07:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0019_auto_20180727_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textfile',
            name='info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'baglan': False, 'balacan': False, 'cagri': False}),
        ),
    ]
